# docker-compose.yml
version: "3.8"

services:
  blockchain:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: ganache --port 8545 --host 0.0.0.0
    networks:
      - app-network

  migrator:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      GANACHE_HOST: blockchain
      GANACHE_PORT: 8545
    depends_on:
      blockchain:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./build/contracts:/build/contracts
    entrypoint: ["bash"]
    command: ["./deploy-contracts.sh"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GANACHE_URL: http://blockchain:8545
      PORT: 5000
      FIREBASE_SERVICE_ACCOUNT_KEY_BASE64: ${FIREBASE_SERVICE_ACCOUNT_KEY_BASE64}
    # --- ADD THIS DEPENDS_ON SECTION BACK ---
    depends_on:
      migrator:
        condition: service_completed_successfully
    # --- END ADD ---
    networks:
      - app-network
    volumes:
      - ./build/contracts:/build/contracts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
