# docker-compose.yml
version: "3.8"

services:
  blockchain:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: ganache --port 8545 --host 0.0.0.0
    networks:
      - app-network

  migrator: # NEW SERVICE: For compiling and deploying smart contracts
    build:
      context: ./contracts # Use the same image as blockchain (has truffle)
      dockerfile: Dockerfile
    environment:
      GANACHE_HOST: blockchain # Point to the blockchain service name
      GANACHE_PORT: 8545
    depends_on:
      blockchain:
        condition: service_started # Wait for blockchain container to start
    networks:
      - app-network
    volumes:
      - ./build/contracts:/build/contracts
    entrypoint: ["bash"] # Keep this to ensure bash is used
    # --- CHANGE THIS COMMAND SECTION ---
    command: ["./deploy-contracts.sh"] # Execute the script
    # --- END CHANGE ---

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GANACHE_URL: http://blockchain:8545
      PORT: 5000
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - app-network
    volumes:
      - ./build/contracts:/build/contracts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
